pipelines:
  pull-requests:
    '**': #this runs as default for any branch not elsewhere defined
      - step:
          name: lint
          image: node:16.14.2
          caches:
            - node
          script:
            - npm ci
            - npm run lint
      - step:
          name: test
          image: docker/compose:1.29.2
          caches:
            - docker
          script:
            - docker-compose -f docker-compose.test.yml up -d
            - docker-compose -f docker-compose.test.yml ps
            - docker-compose -f docker-compose.test.yml run app_server npm run test
            - docker-compose -f docker-compose.test.yml run app_server npm run test:e2e
            - docker-compose -f docker-compose.test.yml run app_server npm run test:cov
            - docker-compose -f docker-compose.test.yml down
          services:
            - docker
definitions:
  services:
    docker:
      memory: 3072
