pipelines:
  pull-requests:
    '**': #this runs as default for any branch not elsewhere defined
      - step:
          name: Lint and test
          image: docker/compose:1.29.2
          script:
            - docker-compose run app_server npm run lint
            - docker-compose run app_server npm run test
            - docker-compose run app_server npm run test:e2e
            - docker-compose run app_server npm run test:cov
          services:
            - docker
definitions:
  services:
    docker:
      memory: 3072
