version: '3'
services:
  test_db:
    container_name: postgres
    image: postgres:13.7-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - '15432:5432'
    volumes:
      - './postgres/:/docker-entrypoint-initdb.d/'

  app_server:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app/node_modules # To prevent overwriting the volume of the host
      - .:/usr/src/app
    env_file:
      - .env.test
    depends_on:
      - test_db
